services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  
.base:
  image: openjdk:8-jdk-alpine
  interruptible: true
  
build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew spotlessCheck build -x test
  
test:
  extends: .base
  stage: test
  script:
    - ./gradlew publishToMavenLocal test
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml

integration-test:
  extends: .base
  stage: test
  script:
    - apk add docker
    - ./gradlew integrationTest
  artifacts:
    reports:
      junit:
        - build/test-results/integrationTest/TEST-*.xml

#coverage:
#  extends: .base
#  stage: test
#  script:
#    - ./gradlew jacocoTestReport && cat build/reports/jacoco/test/jacocoTestReport.csv
#  coverage: '/Code coverage: \d+\.\d+/'

publish-docs:
  image: python:alpine
  interruptible: true
  before_script:
    - pip install mkdocs
    - pip install mkdocs-material
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    refs: 
      - master
    changes:
      - docs/*
      - mkdocs.yml
    
publish-snapshot:
  extends: .base
  stage: deploy
  script:
    - ./gradlew publishAllPublicationsToOssrhRepository
  only:
    - master

publish-release:
  extends: .base
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  only:
    - /^release/.*$/

cache:
  policy: pull
  untracked: true
  key: $CI_PROJECT_ID
  paths:
    - $CI_PROJECT_DIR/.gradle/caches
    - $CI_PROJECT_DIR/.gradle/wrapper
