build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew spotlessCheck publishToMavenLocal build #integrationTest
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
        - build/test-results/integrationTest/TEST-*.xml
