build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew spotlessCheck build jacocoTestReport publishToMavenLocal publishAllPublicationsToOssrhRepository #integrationTest
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
        - build/test-results/integrationTest/TEST-*.xml

pages:
  image: python:alpine
  before_script:
    - pip install mkdocs
    - pip install mkdocs-material
  stage: pages
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public

cache:
  key: $CI_PROJECT_ID
  paths:
    - .gradle/caches
    - .gradle/wrapper
