default:
  image: openjdk:8-jdk-alpine

cache: &global_cache
  policy: pull
  untracked: true
  key: $CI_PROJECT_ID
  paths:
    - $CI_PROJECT_DIR/.gradle/caches
    - $CI_PROJECT_DIR/.gradle/wrapper

build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew spotlessCheck build -x test
  cache:
    <<: *global_cache
    policy: pull-push

test:
  stage: test
  script:
    - ./gradlew publishToMavenLocal test jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
  coverage: '/Total.*?([0-9]{1,3})%/'

integration-test:
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: overlay2
  stage: test
  script:
    - apk add docker
    - ./gradlew integrationTest
#    - cat build/reports/jacoco/jacocoIntegrationTestReport/html/index.html
  artifacts:
    reports:
      junit:
        - build/test-results/integrationTest/TEST-*.xml
#  coverage: '/Total.*?([0-9]{1,3})%/'

publish-docs:
  image: python:alpine
  interruptible: true
  before_script:
    - pip install mkdocs
    - pip install mkdocs-material
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
    changes:
      - docs/*
      - mkdocs.yml

publish-snapshot:
  stage: deploy
  script:
    - ./gradlew publishAllPublicationsToSnapshotsRepository
  only:
    - master

publish-release:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  only:
    - /^release/.*$/
