services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  
build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew spotlessCheck build -x test

test:
  image: openjdk:8-jdk-alpine
  stage: test
  script:
    - ./gradlew publishToMavenLocal test
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
        - build/test-results/integrationTest/TEST-*.xml

integration-test:
  image: openjdk:8-jdk-alpine
  stage: test
  script:
    - apk add docker
    - ./gradlew integrationTest

coverage:
  image: openjdk:8-jdk-alpine
  stage: test
  script:
    - ./gradlew jacocoTestReport

publish-docs:
  image: python:alpine
  before_script:
    - pip install mkdocs
    - pip install mkdocs-material
  stage: deploy
  script:
    - mkdocs build
    - mv site public
    on:
      branch: master
  artifacts:
    paths:
      - public

publish-snapshot:
  image: openjdk:8-jdk-alpine
  stage: deploy
  script:
    - ./gradlew publishAllPublicationsToOssrhRepository

cache:
  key: $CI_PROJECT_ID
  paths:
    - $CI_PROJECT_DIR/.gradle/caches
    - $CI_PROJECT_DIR/.gradle/wrapper
