site_name: Web3j Corda

nav:
  - Quickstart : quickstart.md
  - Getting Started : getting_started.md
  - Connect to Corda Node : connecting_to_node.md
  - Generating Client Wrappers : generating.md
  - Client Wrappers : client.md
  - Using the wrappers : usage.md
  - Command Line Tools: command_line_tools.md
  - Modules : modules.md

# Configuration
theme:
  name: "material"
  logo: "images/web3j-corda-logo.png"
  language: "en"
  feature:
    tabs: true
  palette:
    primary: "white"
    accent: "deep-orange"

markdown_extensions:
  - pymdownx.tasklist

extra_css:
  - "stylesheets/extra.css"
#  - "stylesheets/github.css"

#extra_javascript:
#  - 'javascripts/highlight.pack.js'
#  - 'javascripts/index.js'
